name: Release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2

      - run: deno publish

      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
